export const types = {
  //authentication

  GENERATE_OTP: "GENERATE_OTP",
  GET_OTP_FOR_VERIFICATION:'GET_OTP_FOR_VERIFICATION',
  VERIFY_OTP: "VERIFY_OTP",
  RESET_PASSWORD: "RESET_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  GENERATE_FORGOT_PWD_OTP: "GET_FORGOT_PWD_OTP",
  SET_CURRENT_USER_DATA: "SET_CURRENT_USER_DATA",
  SET_LOGIN_DATA: "SET_LOGIN_DATA",
  LOGOUT: "LOGOUT",
  POSTER_SIGN_UP: "POSTER_SIGN_UP",
  POSTER_LOGIN: "POSTER_LOGIN",
  SET_POSTER_DATA: "SET_POSTER_DATA",
  GENERATE_OTP: "GENERATE_OTP",
  RESET_PASSWORD: "RESET_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  SET_CURRENT_USER_DATA: "SET_CURRENT_USER_DATA",
  SET_LOGIN_DATA: "SET_LOGIN_DATA",
  GENERATE_OTP_FORGOT_PASSWORD: "GENERATE_OTP_FORGOT_PASSWORD",
};
